<Project>

    <PropertyGroup>
        <HistoricRelationships Condition="'$(HistoricRelationships)' == ''">false</HistoricRelationships>
        <AlphaRelease Condition="'$(AlphaRelease)' == ''">false</AlphaRelease>
    </PropertyGroup>

    <PropertyGroup Condition="'$(HistoricRelationships)' == 'true'">
        <DefineConstants>$(DefineConstants);HISTORIC_RELATIONSHIPS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(AlphaRelease)' == 'true'">
        <DefineConstants>$(DefineConstants);ALPHA_RELEASE</DefineConstants>
    </PropertyGroup>

</Project>
