<Project>

    <PropertyGroup>
        <AlphaRelease Condition="'$(AlphaRelease)' == ''">false</AlphaRelease>
    </PropertyGroup>

    <PropertyGroup Condition="'$(AlphaRelease)' == 'true'">
        <DefineConstants>$(DefineConstants);ALPHA_RELEASE</DefineConstants>
    </PropertyGroup>

</Project>
